# Generated by Django 5.2.11 on 2026-02-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('slot', 'semester_course')},
        ),
    ]
